set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[63]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[62]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[61]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[60]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[59]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[58]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[57]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[56]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[55]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[54]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[53]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[52]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[51]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[50]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[49]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[48]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[47]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[46]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[45]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[44]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[43]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[42]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[41]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[40]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[39]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[38]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[37]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[36]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[35]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[34]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[33]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOBits[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]


set_property OFFCHIP_TERM NONE [get_ports IOBits[0]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[10]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[11]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[12]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[13]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[14]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[15]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[16]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[17]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[18]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[19]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[1]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[20]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[21]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[22]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[23]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[24]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[25]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[26]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[27]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[28]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[29]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[2]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[30]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[31]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[32]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[33]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[3]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[4]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[5]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[6]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[7]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[8]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[9]]

set_property OFFCHIP_TERM NONE [get_ports IOBits[34]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[35]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[36]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[37]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[38]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[39]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[40]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[41]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[42]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[43]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[44]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[45]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[46]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[47]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[48]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[49]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[50]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[51]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[52]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[53]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[54]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[55]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[56]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[57]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[58]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[60]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[61]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[62]]
set_property OFFCHIP_TERM NONE [get_ports IOBits[63]]


set_property OFFCHIP_TERM NONE [get_ports LED[2]]
set_property OFFCHIP_TERM NONE [get_ports LED[1]]
set_property OFFCHIP_TERM NONE [get_ports LED[0]]


set_property PACKAGE_PIN R14 [get_ports {LED[2]}]
set_property PACKAGE_PIN Y16 [get_ports {LED[1]}]
set_property PACKAGE_PIN Y17 [get_ports {LED[0]}]

set_property PACKAGE_PIN R19 [get_ports {IOBits[0]}]
set_property PACKAGE_PIN T19 [get_ports {IOBits[1]}]
set_property PACKAGE_PIN G14 [get_ports {IOBits[2]}]
set_property PACKAGE_PIN J15 [get_ports {IOBits[3]}]
set_property PACKAGE_PIN P14 [get_ports {IOBits[4]}]
set_property PACKAGE_PIN C20 [get_ports {IOBits[5]}]
set_property PACKAGE_PIN U15 [get_ports {IOBits[6]}]
set_property PACKAGE_PIN B20 [get_ports {IOBits[7]}]
set_property PACKAGE_PIN W14 [get_ports {IOBits[8]}]
set_property PACKAGE_PIN T14 [get_ports {IOBits[9]}]
set_property PACKAGE_PIN Y14 [get_ports {IOBits[10]}]
set_property PACKAGE_PIN T15 [get_ports {IOBits[11]}]
set_property PACKAGE_PIN T11 [get_ports {IOBits[12]}]
set_property PACKAGE_PIN U13 [get_ports {IOBits[13]}]
set_property PACKAGE_PIN T10 [get_ports {IOBits[14]}]
set_property PACKAGE_PIN V13 [get_ports {IOBits[15]}]
set_property PACKAGE_PIN T12 [get_ports {IOBits[16]}]
set_property PACKAGE_PIN V12 [get_ports {IOBits[17]}]
set_property PACKAGE_PIN U12 [get_ports {IOBits[18]}]
set_property PACKAGE_PIN W13 [get_ports {IOBits[19]}]
set_property PACKAGE_PIN A20 [get_ports {IOBits[20]}]
set_property PACKAGE_PIN B19 [get_ports {IOBits[21]}]
set_property PACKAGE_PIN D18 [get_ports {IOBits[22]}]
set_property PACKAGE_PIN E17 [get_ports {IOBits[23]}]
set_property PACKAGE_PIN D20 [get_ports {IOBits[24]}]
set_property PACKAGE_PIN D19 [get_ports {IOBits[25]}]
set_property PACKAGE_PIN E19 [get_ports {IOBits[26]}]
set_property PACKAGE_PIN E18 [get_ports {IOBits[27]}]
set_property PACKAGE_PIN F17 [get_ports {IOBits[28]}]
set_property PACKAGE_PIN F16 [get_ports {IOBits[29]}]
set_property PACKAGE_PIN M20 [get_ports {IOBits[30]}]
set_property PACKAGE_PIN M19 [get_ports {IOBits[31]}]
set_property PACKAGE_PIN M18 [get_ports {IOBits[32]}]
set_property PACKAGE_PIN M17 [get_ports {IOBits[33]}]


set_property PACKAGE_PIN L20 [get_ports {IOBits[34]}]
set_property PACKAGE_PIN L19 [get_ports {IOBits[35]}]
set_property PACKAGE_PIN J19 [get_ports {IOBits[36]}]
set_property PACKAGE_PIN K19 [get_ports {IOBits[37]}]
set_property PACKAGE_PIN L17 [get_ports {IOBits[38]}]
set_property PACKAGE_PIN L16 [get_ports {IOBits[39]}]
set_property PACKAGE_PIN K18 [get_ports {IOBits[40]}]
set_property PACKAGE_PIN H17 [get_ports {IOBits[41]}]
set_property PACKAGE_PIN H18 [get_ports {IOBits[42]}]
set_property PACKAGE_PIN J18 [get_ports {IOBits[43]}]
set_property PACKAGE_PIN F20 [get_ports {IOBits[44]}]
set_property PACKAGE_PIN F19 [get_ports {IOBits[45]}]
set_property PACKAGE_PIN G18 [get_ports {IOBits[46]}]
set_property PACKAGE_PIN G17 [get_ports {IOBits[47]}]
set_property PACKAGE_PIN H20 [get_ports {IOBits[48]}]
set_property PACKAGE_PIN J20 [get_ports {IOBits[49]}]
set_property PACKAGE_PIN G20 [get_ports {IOBits[50]}]
set_property PACKAGE_PIN G19 [get_ports {IOBits[51]}]
set_property PACKAGE_PIN G15 [get_ports {IOBits[52]}]
set_property PACKAGE_PIN H15 [get_ports {IOBits[53]}]
set_property PACKAGE_PIN J14 [get_ports {IOBits[54]}]
set_property PACKAGE_PIN K14 [get_ports {IOBits[55]}]


# j7
set_property PACKAGE_PIN T9  [get_ports {IOBits[56]}]
set_property PACKAGE_PIN U7  [get_ports {IOBits[57]}]
set_property PACKAGE_PIN U10 [get_ports {IOBits[58]}]
set_property PACKAGE_PIN V7  [get_ports {IOBits[59]}]
set_property PACKAGE_PIN Y9  [get_ports {IOBits[60]}]
set_property PACKAGE_PIN Y7  [get_ports {IOBits[61]}]
set_property PACKAGE_PIN Y8  [get_ports {IOBits[62]}]
set_property PACKAGE_PIN Y6  [get_ports {IOBits[63]}]


# J3 pins 36-40
# http://static.mah.priv.at/public/Z-turn%20IO%20Cape%20User%20Guide.pdf
# 1.1.1 I/O
#set_property PACKAGE_PIN G19 [get_ports {RATES[0]}]   # IO_B35_LP18
#set_property PACKAGE_PIN G15 [get_ports {RATES[1]}]   # IO_B35_LN19
#set_property PACKAGE_PIN H15 [get_ports {RATES[2]}]   # IO_B35_LP19
#set_property PACKAGE_PIN J14 [get_ports {RATES[3]}]   # IO_B35_LN20
#set_property PACKAGE_PIN K14 [get_ports {RATES[4]}]   # IO_B35_LP20

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

